name: samdev
channels:
  - conda-forge
  - default
dependencies:
  - awscli
  - boto3
  - sqlite
  - click
  - pip
  - pytz
  - requests
  - jq
  - git
  - python==3.12.*
  - termcolor
  - packaging
  - ruff
