# Allow Ctrl+B -> M : to toggle mouse mode on/off
# mouse off allow allows for highlight and copy
# mouse on allows for scrolling up in tmux output
bind m set -g mouse \; display "Mouse: #{?mouse,ON,OFF}"

set -s set-clipboard on
